name: Lint and Test

on: [push]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: make install
    - name: Lint
      run: make lint
    - name: Test
      run: make test
